release v0.6.0 (#11)
* feat(templates): tweaked

* fix(workflows): preventing workflows from triggering both self and main

* feat(templates): cleaned templates, removing unnecessary elements

* feat(template): simplification

* feat(cleanup): cleaned docs and cicd

* fix(build-and-tes): fixed reference to publish-on-release

* ci(naming): shortened run names

* fix(build-and-test): added pip for smoke testing

* bump: version 0.1.0 → 0.2.0

* feat(repo_template): added ci-orchestrator.yaml to git keep

* bump: version 0.2.0 → 0.3.0

* fix(post-release-private): fixed triggering of back sync

* bump: version 0.3.0 → 0.4.0

* feat(sync-from-public): added for downstream templating

* bump: version 0.4.0 → 0.5.0

* fix(public-release): entered correct private/public repos

* bump: version 0.5.0 → 0.6.0

* feat(back-sync-release): prevent running of tests

diff --git a/.github/workflows/ensure-release-source.yaml b/.github/workflows/ensure-release-source.yaml
--- a/.github/workflows/ensure-release-source.yaml
+++ b/.github/workflows/ensure-release-source.yaml
@@ -77,16 +77,6 @@ jobs:
         base="${{ github.base_ref }}"
         head="${{ github.head_ref }}"
 
-        if [ "$repo" = "$PRIVATE_REPO" ] && [ "$base" = "$PRIVATE_REPO_RELEASE_BRANCH" ]; then
-          if [ "$head" != "$PRIVATE_REPO_MAIN_BRANCH" ]; then
-            echo "ERROR: PRs into '$PRIVATE_REPO_RELEASE_BRANCH' must come from '$PRIVATE_REPO_MAIN_BRANCH'."
-            echo "Actual source branch: '$head'"
-            exit 1
-          fi
-          echo "Private release route allowed: $head -> $base"
-          exit 0
-        fi
-
         if [ "$repo" = "$PUBLIC_REPO" ] && [ "$base" = "$PUBLIC_REPO_RELEASE_BRANCH" ]; then
           if [ "$head" != "$PUBLIC_REPO_INCOMING_BRANCH" ]; then
             echo "ERROR: PRs into '$PUBLIC_REPO_RELEASE_BRANCH' must come from '$PUBLIC_REPO_INCOMING_BRANCH'."
@@ -94,6 +84,16 @@ jobs:
             exit 1
           fi
           echo "Public release route allowed: $head -> $base"
+          exit 0
+        fi
+
+        if [ "$repo" = "$PRIVATE_REPO" ] && [ "$base" = "$PRIVATE_REPO_RELEASE_BRANCH" ]; then
+          if [ "$head" != "$PRIVATE_REPO_MAIN_BRANCH" ]; then
+            echo "ERROR: PRs into '$PRIVATE_REPO_RELEASE_BRANCH' must come from '$PRIVATE_REPO_MAIN_BRANCH'."
+            echo "Actual source branch: '$head'"
+            exit 1
+          fi
+          echo "Private release route allowed: $head -> $base"
           exit 0
         fi
 
